// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9K2KtlNUXb84goK3Tn9syK03xLBNL1Q0',
    appId: '1:145851234477:web:309624002d5bfb83e12e24',
    messagingSenderId: '145851234477',
    projectId: 'noamapp-399dc',
    authDomain: 'noamapp-399dc.firebaseapp.com',
    storageBucket: 'noamapp-399dc.firebasestorage.app',
    measurementId: 'G-6DHJ7XCJ77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqewAJlUa7WEVLIH4z3V0LEp4Q81-stv4',
    appId: '1:145851234477:android:994aee311bccd7a1e12e24',
    messagingSenderId: '145851234477',
    projectId: 'noamapp-399dc',
    storageBucket: 'noamapp-399dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV7AZPg92hHJFWdDEhv413611iSFkNTQU',
    appId: '1:145851234477:ios:c1c0df60a517f547e12e24',
    messagingSenderId: '145851234477',
    projectId: 'noamapp-399dc',
    storageBucket: 'noamapp-399dc.firebasestorage.app',
    iosBundleId: 'com.example.noamapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV7AZPg92hHJFWdDEhv413611iSFkNTQU',
    appId: '1:145851234477:ios:c1c0df60a517f547e12e24',
    messagingSenderId: '145851234477',
    projectId: 'noamapp-399dc',
    storageBucket: 'noamapp-399dc.firebasestorage.app',
    iosBundleId: 'com.example.noamapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9K2KtlNUXb84goK3Tn9syK03xLBNL1Q0',
    appId: '1:145851234477:web:3a027a4088f4350ce12e24',
    messagingSenderId: '145851234477',
    projectId: 'noamapp-399dc',
    authDomain: 'noamapp-399dc.firebaseapp.com',
    storageBucket: 'noamapp-399dc.firebasestorage.app',
    measurementId: 'G-QJ9FNNJ0LB',
  );
}
